on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: 
          - {os: ubuntu-latest, pip: ~/.cache/pip}
          - {os: macos-latest, pip: ~/Library/Caches/pip}
          - {os: windows-latest, pip: ~\AppData\Local\pip\Cache}
        python: [ '3.8', '3.9' ]
  name: ${{ matrix.config.os }} Python ${{ matrix.python }} 
  steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Cache
      with:
        path: ${{ matrix.config.pip }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        resutore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: python -m unittest discover 


